test-rabbitmq:
  image: rabbitmq:3.6.6-management
  container_name: test-rabbitmq
  environment:
    - RABBITMQ_DEFAULT_USER=test
    - RABBITMQ_DEFAULT_PASS=test
    - RABBITMQ_DEFAULT_VHOST=test
  ports:
    - "5672:5672"
    - "15672:15672"
  restart: always
